name: Check

on:
  push:
    branches:
      - master
  pull_request:
    branches: ['*']

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run lint, unit and e2e tests
        run: npm run lint && npm run test && npm run cypress:run
