name: Публикация на GitHub Pages

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Загрузка артефактов сборки
        uses: actions/download-artifact@v4
        with:
          name: actions_artifacts
          path: dist

      - name: Загрузка артефактов в Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/'

      - name: Развёртывание на GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
