name: Публикация на GitHub Pages

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Загрузка артефактов сборки
        uses: actions/download-artifact@v4
        with:
          name: actions_artifacts
          path: actions_artifacts

      - name: Развёртывание на GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: actions_artifacts/dist
          clean: true
          commit-message: '✔️ Сборка для GitHub Pages'
